Get-ChildItem -Filter *.js | ForEach-Object {
    $filename = $_.FullName
    Write-Host "Processing file: $filename"
    # 使用UTF-8编码读取文件
    $content = [System.IO.File]::ReadAllText($filename, [System.Text.Encoding]::UTF8)
    # 执行替换操作
    $content = $content -replace 'if \(num\)', 'if (num > 0)'
    $content = $content -replace 'while \(num--\)', 'while (num-- > 0)'
    $content = $content -replace 'while \(count--\)', 'while (count-- > 0)'
    $content = $content -replace 'while \(num\)', 'while (num > 0)'
    $content = $content -replace 'while \(count\)', 'while (count > 0)'
    $content = $content -replace "' && range\[1\]", "' && Array.isArray(range) && range[1]"
    $content = $content -replace '\(range\[1\]', '(Array.isArray(range) && range[1]'
    $content = $content -replace '\.contains\(', '.includes('
    $content = $content -replace '\.animate\(', '.addTempClass('
    $content = $content -replace 'classList\.includes', 'classList.contains'
    $content = $content -replace 'ui\.arena\.includes', 'ui.arena.contains'
    $content = $content -replace 'ui\.window\.includes', 'ui.window.contains'
    $content = $content -replace 'ui\.cardPile\.includes', 'ui.cardPile.contains'
    $content = $content -replace 'if \(arg\.', 'if (arg && arg.'
    $content = $content -replace '\.length > 0', '.length'
    $content = $content -replace '\.storage\.disableEquip\.length', '.countDisabled()'    
    $content = $content -replace 'priority:', '_priority:'
    $content = $content -replace '__priority', '_priority'
    $content = $content -replace '\s\s\s_priority: 0,', ''
    $content = $content -replace 'chooseToUse\(true, ', 'chooseToUse('
    $content = $content -replace 'player\.storage\.disableEquip != undefined && player\.storage\.disableEquip\.length', 'player.countDisabled()'
    $content = $content -replace "' \+ '", ''
    $content = $content -replace "'forbidai'", ''
    $content = $content -replace 'filter: function \(event\)', 'filter: function (event, player)'
    $content = $content -replace 'filter: function \(\)', 'filter: function (event, player)'
    $content = $content -replace 'filterCard: function \(card\)', 'filterCard: function (card, player)'
    $content = $content -replace '9999', '999'
    $content = $content -replace '114514', '999'
    $content = $content -replace 'player\.recover\(player\.maxHp - player\.hp\)', 'player.hp = player.maxHp'
    $content = $content -replace 'player\.recover\(Infinity\)', 'player.hp = player.maxHp'
    $content = $content -replace 'target\.recover\(Infinity\)', 'target.hp = target.maxHp'
    $content = $content -replace 'target\.recover\(999\);', 'target.hp = target.maxHp;'
    $content = $content -replace 'player\.recover\(999\);', 'player.hp = player.maxHp;'
    $content = $content -replace 'for \(i', 'for (let i'
    $content = $content -replace 'for \(var i =', 'for (let i ='
    $content = $content -replace 'for \(var i of', 'for (const i of'
    $content = $content -replace 'for \(let i = 0; i < game\.players\.length; i\+\+\)', 'for (const i of game.players)'
    $content = $content -replace 'game\.players\[i\]', 'i'
    $content = $content -replace 'for \(let i = 0; i < event\.players\.length; i\+\+\)', 'for (const i of event.players)'
    $content = $content -replace 'event\.players\[i\]', 'i'
    $content = $content -replace 'for \(let i = 0; i < trigger\.players\.length; i\+\+\)', 'for (const i of trigger.players)'
    $content = $content -replace 'trigger\.players\[i\]', 'i'
    $content = $content -replace 'for \(let i = 0; i < result\.links\.length; i\+\+\)', 'for (const i of result.links)'
    $content = $content -replace 'result\.links\[i\]', 'i'
    $content = $content -replace 'for \(let i = 0; i < event\.cards\.length; i\+\+\)', 'if (Array.isArray(event.cards)) for (const i of event.cards)'
    $content = $content -replace 'event\.cards\[i\]', 'i'
    $content = $content -replace 'for \(let i = event\.cards\.length - 1; i >= 0; i--\)', 'if (Array.isArray(event.cards)) for (const i of event.cards)'
    $content = $content -replace 'for \(let i = 0; i < trigger\.cards\.length; i\+\+\)', 'if (Array.isArray(trigger.cards)) for (const i of trigger.cards)'
    $content = $content -replace 'trigger\.cards\[i\]', 'i'
    $content = $content -replace 'for \(let i = 0; i < result\.cards\.length; i\+\+\)', 'if (Array.isArray(result.cards)) for (const i of result.cards)'
    $content = $content -replace 'result\.cards\[i\]', 'i'
    $content = $content -replace 'for \(let i = 0; i < ui\.selected\.cards\.length; i\+\+\)', 'if (Array.isArray(ui.selected.cards)) for (const i of ui.selected.cards)'
    $content = $content -replace 'ui\.selected\.cards\[i\]', 'i'
    $content = $content -replace 'for \(let i = 0; i < evt\.cards\.length; i\+\+\)', 'if (Array.isArray(evt.cards)) for (const i of evt.cards)'
    $content = $content -replace 'evt\.cards\[i\]', 'i'
    $content = $content -replace 'return event\.source\.', 'return event.source && event.source.'
    $content = $content -replace 'return event\.cards\.', 'return event.cards && event.cards.'
    $content = $content -replace 'return event\.card\.', 'return event.card && event.card.'
    $content = $content -replace '\(evt\.filterCard\(', '(evt.filterCard && evt.filterCard('
    $content = $content -replace '\(!event\.filterCard\(', '(!event.filterCard || !event.filterCard('
    $content = $content -replace '\(event\.filterCard\(', '(event.filterCard && event.filterCard('
    $content = $content -replace "。'", "'"
    $content = $content -replace '。', '.'
    $content = $content -replace '，', ','
    $content = $content -replace '；', ';'
    $content = $content -replace '：', ':'
    $content = $content -replace '（', '('
    $content = $content -replace '）', ')'
    $content = $content -replace '“', '<'
    $content = $content -replace '”', '>'
    $content = $content -replace '》', '>'
    $content = $content -replace '《', '<'
    $content = $content -replace '！', '!'
    $content = $content -replace 'globalFixed: true,', ''    
    $content = $content -replace 'Object\.defineProperty', 'Reflect.defineProperty'
    $content = $content -replace 'configurable: false,', ''
    $content = $content -replace 'configurable: true,', ''
    $content = $content -replace 'frequent: true,', 'forced: true,'
    $content = $content -replace 'direct: true,', 'forced: true,'
    $content = $content -replace 'locked: true,', ''
    $content = $content -replace 'locked: false,', ''
    $content = $content -replace 'forced: false,', ''
    $content = $content -replace '\s\s\slog: false,', ''
    $content = $content -replace 'forceunique: true,', ''
    $content = $content -replace '\s\s\sunique: true,', ''
    $content = $content -replace 'noRemove: true,', ''
    $content = $content -replace 'noDisabled: true,', ''
    $content = $content -replace 'noDeprive: true,', ''
    $content = $content -replace 'nolose: true,', ''
    $content = $content -replace 'noGain: true,', ''
    $content = $content -replace 'noAdd: true,', ''
    $content = $content -replace 'sub: true,', ''
    $content = $content -replace 'onremove: true,', ''
    $content = $content -replace 'onunmark: true,', ''
    $content = $content -replace 'audio: false,', ''
    $content = $content -replace 'vanish: true,', ''
    $content = $content -replace 'destroy: true,', ''
    $content = $content -replace ', isCard: true', ''
    $content = $content -replace 'isCard: true,', ''
    $content = $content -replace ': function', ''
    $content = $content -replace 'content\*', 'content: function*'
    $content = $content -replace '方片', '♦️'
    $content = $content -replace '方块', '♦️'
    $content = $content -replace '♦', '♦️'
    $content = $content -replace '梅花', '♣️'    
    $content = $content -replace '草花', '♣️'
    $content = $content -replace '♣', '♣️'
    $content = $content -replace '红桃', '♥️'
    $content = $content -replace '红心', '♥️'
    $content = $content -replace '♥', '♥️'
    $content = $content -replace '黑桃', '♠️'
    $content = $content -replace '♠', '♠️'
    $content = $content -replace '无色', '🃏'
    $content = $content -replace '无花色', '🃏'
    $content = $content -replace '无颜色', '🃏'
    $content = $content -replace 'else return', 'return'
    $content = $content -replace 'unequip_ai', 'unequip'
    $content = $content -replace 'trigger\.card2\.number', 'trigger.num2'
    $content = $content -replace 'trigger\.card1\.number', 'trigger.num1'
    $content = $content -replace 'event\.card2\.number', 'event.num2'
    $content = $content -replace 'event\.card1\.number', 'event.num1'
    $content = $content -replace 'editable: false,', ''
    $content = $content -replace '\.getParent\(\)', '.parent'
    $content = $content -replace '\.getSeatNum\(\)', '.seatNum'
    $content = $content -replace '(.+)\.setSeatNum\((.+)\);', '$1.seatNum = $2;'
    $content = $content -replace '\.getNext\(\)', '.next'
    $content = $content -replace '\.getPrevious\(\)', '.previous'
    $content = $content -replace '\.animate\(', '.addTempClass('
    $content = $content -replace 'ai\.get\.attitude', 'get.attitude'
    $content = $content -replace 'ai\.get\.value', 'get.value'
    $content = $content -replace '\[,', '['
    $content = $content -replace ',\]', ']'
    $content = $content -replace ',,', ','
    $content = $content -replace ', ,', ','
    $content = $content -replace "var chat = \[('[^']*')\]\.randomGet\(\);\n\s*player\.say\(chat\);", 'player.say($1);'
    $content = $content -replace 'get.autoViewAs\(\{([^()]*)\}[^()]*\)', '{$1}'
    $content = $content -replace 'get.autoViewAs\(([^,()]*)\)', '$1'
    $content = $content -replace '\(new lib\.element\.VCard\(\{([^}]*)\}\)', '({$1}'
    $content = $content -replace ': \(([^(]*)\) => \{', '($1){'
    $content = $content -replace 'get.number\(([^()]*),[^()]*\)', '$1.number'  
    $content = $content -replace 'get.number\(([^()]*)\)', '$1.number'
    $content = $content -replace 'get.suit\(([^()]*),[^()]*\)', '$1.suit'
    $content = $content -replace 'get.suit\(([^()]*)\)', '$1.suit'
    $content = $content -replace 'get.name\(([^()]*),[^()]*\)', '$1.name'
    $content = $content -replace 'get.name\(([^()]*)\)', '$1.name'
    $content = $content -replace '\s\s\sconsole\.log\(.+\);', ''
    $content = $content -replace '\s\s\sgame\.delay\(.*\);', ''
    $content = $content -replace '\s\s\sgame\.delayx\(.*\);', ''
    $content = $content -replace '\s\s\s\S+\.logSkill\(.*\);', ''
    $content = $content -replace '\s\s\snext\.logSkill = .+;', '' 
    $content = $content -replace '\)\.logSkill = .+;', ');' 
    $content = $content -replace "\s\s\snext\.set\('logSkill', .+\);", '' 
    $content = $content -replace "\)\.set\('logSkill', .+\);", ');' 
    $content = $content -replace "\.set\('logSkill', [^()]*\)", '' 
    $content = $content -replace '\s\s\sskillAnimation:.+,', ''
    $content = $content -replace '\s\s\sanimationColor:.+,', ''
    $content = $content -replace '\n\n', [Environment]::NewLine
    $content = $content -replace '\n\s*\n', [Environment]::NewLine
    $content = $content -replace "(?<![\s:,[(=])\['([^··\.' --+\d]*)'\]", '.$1' 
    $content = $content -replace 'forced: true,\n\s*forced: true,', 'forced: true,' 
    $content = $content -replace '\s\s\s\S+.updateMark\(.+\);', '' 
    $content = $content -replace '\s\s\s\S+\.updateMarks\(\);', '' 
    $content = $content -replace '\s\s\s\S+\.updateMarks\(.+\);', '' 
    $content = $content -replace '\s\s\s\S+\.syncStorage\(.+\);', '' 
    $content = $content -replace 'color:#', 'color: #' 
    $content = $content -replace 'color:rgb', 'color: rgb' 
    $content = $content -replace "mark: 'character',", ''
    $content = $content -replace '!([^&(|]*)\.isFriendsOf\(', '$1.isEnemiesOf('
    $content = $content -replace '!([^&(|]*)\.isEnemiesOf\(', '$1.isFriendsOf('
    $content = $content -replace 'isFriendOf', 'isFriendsOf'
    $content = $content -replace 'isEnemyOf', 'isEnemiesOf'
    $content = $content -replace '!player\.getFriends\(true\)\.includes', 'player.getEnemies().includes'
    $content = $content -replace '!player\.getFriends\(\)\.includes', 'player.getEnemies().includes'
    $content = $content -replace '!player\.getEnemies\(\)\.includes', 'player.getFriends(true).includes'
    $content = $content -replace 'event\.count = trigger\.num;', 'event.count = Math.min(trigger.num, 9);'
    $content = $content -replace 'event\.num = trigger\.num;', 'event.num = Math.min(trigger.num, 9);'
    $content = $content -replace '恢复', '回复'
    $content = $content -replace '杀死', '击杀'
    $content = $content -replace '\.insertPhase\(\)', ".phase('nodelay')"
    $content = $content -replace '\.phase\(\)', ".phase('nodelay')"
    $content = $content -replace "marktext: '<img style=width:.+px height:.+px src=(.+)\.jpg>',", "markimage: '$1.jpg',"
    $content = $content -replace "marktext: '<img style=width:.+px src=(.+)\.jpg>',", "markimage: '$1.jpg',"
    $content = $content -replace "marktext: '<img style=width:.+px height:.+px src=(.+)\.png>',", "markimage: '$1.png',"
    $content = $content -replace "marktext: '<img style=width:.+px src=(.+)\.png>',", "markimage: '$1.png',"
    $content = $content -replace 'console\.error', 'console.warn'
    $content = $content -replace 'indexOf\(([^)]*)\) != -1', 'includes($1)'
    $content = $content -replace '', ''
    $content = $content -replace '', ''
    $content = $content -replace '', ''
    $content = $content -replace '', ''
    $content = $content -replace '', ''
    # 使用UTF-8编码写回文件
    [System.IO.File]::WriteAllText($filename, $content, [System.Text.Encoding]::UTF8)
    Write-Host "Replacements complete for $filename"
}
Write-Host "All replacements completed."